### ISSUE TITLE
Error:E013:Insufficient Private Resources! 

### ISSUE THREAD

**Issue by kolik33** [nginnever/zogminer#10]
Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Tahiti
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 936378368
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 649592832
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [Tahiti] with 936378368 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1800.11))
[OPENCL]:"/tmp/OCL749eEA.cl", line 94: warning: arithmetic on pointer to void or
          function type
      for ( ; n-- ; s1++, s2++) {
                      ^

"/tmp/OCL749eEA.cl", line 94: warning: arithmetic on pointer to void or
          function type
      for ( ; n-- ; s1++, s2++) {
                            ^

"/tmp/OCL749eEA.cl", line 130: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
    memcpy(&w, src, sizeof w);
               ^

"/tmp/OCL749eEA.cl", line 137: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
    memcpy(&w, src, sizeof w);
               ^

"/tmp/OCL749eEA.cl", line 229: warning: integer conversion resulted in a
          change of sign
    S->f[1] = -1;
              ^

"/tmp/OCL749eEA.cl", line 249: warning: integer conversion resulted in a
          change of sign
    S->f[0] = -1;
              ^

"/tmp/OCL749eEA.cl", line 384: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
      memcpy( block, key, keylen );
                     ^

"/tmp/OCL749eEA.cl", line 464: warning: argument of type "const uint8_t *" is
          incompatible with parameter of type "void *"
        memcpy( S->buf + left, in, fill ); /* Fill buffer */
                               ^

"/tmp/OCL749eEA.cl", line 475: warning: argument of type "const uint8_t *" is
          incompatible with parameter of type "void *"
        memcpy( S->buf + left, in, inlen );
                               ^

"/tmp/OCL749eEA.cl", line 730: warning: variable "bucket" was declared but
          never referenced
          __global bucket_t* bucket = src + i;
                             ^

"/tmp/OCL749eEA.cl", line 732: warning: variable "sub_buckets" was declared
          but never referenced
          uint32_t sub_buckets[NUM_INDICES_PER_BUCKET][20];
                   ^

"/tmp/OCL749eEA.cl", line 718: warning: variable "n_solutions" was declared
          but never referenced
      uint32_t n_solutions = 0;
               ^

"/tmp/OCL749eEA.cl", line 719: warning: variable "start_bit" was declared but
          never referenced
      size_t start_bit = ((EQUIHASH_K-1) * NUM_COLLISION_BITS);
             ^

"/tmp/OCL749eEA.cl", line 720: warning: variable "last_bit" was declared but
          never referenced
      size_t last_bit = ((EQUIHASH_K) * NUM_COLLISION_BITS);
             ^

"/tmp/OCL749eEA.cl", line 724: warning: variable "indices" was set but never
          used
      __global element_indice_t* indices[9];
                                 ^

"/tmp/OCL749eEA.cl", line 127: warning: function "load32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) load32( const void *src )
                                ^

"/tmp/OCL749eEA.cl", line 151: warning: function "load48" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint64_t) load48( const void *src )
                                ^

"/tmp/OCL749eEA.cl", line 163: warning: function "store48" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(void) store48( void *dst, uint64_t w )
                            ^

"/tmp/OCL749eEA.cl", line 174: warning: function "rotl32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) rotl32( const uint32_t w, const unsigned c )
                                ^

"/tmp/OCL749eEA.cl", line 179: warning: function "rotl64" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint64_t) rotl64( const uint64_t w, const unsigned c )
                                ^

"/tmp/OCL749eEA.cl", line 184: warning: function "rotr32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) rotr32( const uint32_t w, const unsigned c )
                                ^

"/tmp/OCL749eEA.cl", line 253: warning: function "blake2b_clear_lastblock" was
          declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_clear_lastblock( blake2b_state *S )
                           ^

"/tmp/OCL749eEA.cl", line 271: warning: function
          "blake2b_param_set_digest_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_digest_length( blake2b_param *P, const uint8_t digest_length )
                           ^

"/tmp/OCL749eEA.cl", line 277: warning: function "blake2b_param_set_fanout"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_fanout( blake2b_param *P, const uint8_t fanout )
                           ^

"/tmp/OCL749eEA.cl", line 283: warning: function "blake2b_param_set_max_depth"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_max_depth( blake2b_param *P, const uint8_t depth )
                           ^

"/tmp/OCL749eEA.cl", line 289: warning: function
          "blake2b_param_set_leaf_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_leaf_length( blake2b_param *P, const uint32_t leaf_length )
                           ^

"/tmp/OCL749eEA.cl", line 295: warning: function
          "blake2b_param_set_node_offset" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_offset( blake2b_param *P, const uint64_t node_offset )
                           ^

"/tmp/OCL749eEA.cl", line 301: warning: function "blake2b_param_set_node_depth"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_depth( blake2b_param *P, const uint8_t node_depth )
                           ^

"/tmp/OCL749eEA.cl", line 307: warning: function
          "blake2b_param_set_inner_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_inner_length( blake2b_param *P, const uint8_t inner_length )
                           ^

Error:E013:Insufficient Private Resources!

what is the reason? Ubuntu 14.04

**Comment by omaralvarez** [comment]
This should be due to your card's OpenCL specs not being capable of supporting as much private memory as the kernel needs in its current state. We will try to improve the kernels to use less resources after we have a full solver.

**Comment by kolik33** [comment]
Thank you, we look forward to

**Comment by nginnever** [comment]
this should not be relevant with current build
