### ISSUE TITLE
Multi-GPU does not work now... ?

### ISSUE THREAD

**Issue by aleksfox** [nginnever/zogminer#11]
I have 2 GPU, but test miner does not use one of them.

Zcash Miner version v1.0.0-beta2-f6baa2f (2016-10-21 13:19:08 +0200)
Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8515809280
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8270716928
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [Ellesmere] with 8515809280 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Ellesmere(OpenCL 1.2 AMD-APP (2117.7))
[OPENCL]:Printing program log
[OPENCL]:/tmp/OCL3061T5.cl:130:14: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
  memcpy(&w, src, sizeof w);
             ^~~
/tmp/OCL3061T5.cl:116:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL3061T5.cl:137:14: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
  memcpy(&w, src, sizeof w);
             ^~~
/tmp/OCL3061T5.cl:116:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL3061T5.cl:384:20: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
    memcpy( block, key, keylen );
                   ^~~
/tmp/OCL3061T5.cl:116:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL3061T5.cl:464:30: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
      memcpy( S->buf + left, in, fill ); /* Fill buffer */
                             ^~
/tmp/OCL3061T5.cl:116:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL3061T5.cl:475:30: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
      memcpy( S->buf + left, in, inlen );
                             ^~
/tmp/OCL3061T5.cl:116:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
5 warnings generated.

Running Equihash solver with nNonce = 0000000000000000000000000000000000000000000000000000000000000000
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Kernel run took 184 ms. (5.43478 H/s)
Solver took 457.75 Mcycles

Running Equihash solver with nNonce = 0000000000000000000000000000000000000000000000000000000000000001
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Kernel run took 121 ms. (8.26446 H/s)
Solver took 302.47 Mcycles

Running Equihash solver with nNonce = 0000000000000000000000000000000000000000000000000000000000000002
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Kernel run took 121 ms. (8.26446 H/s)
Solver took 303.10 Mcycles

**Comment by nginnever** [comment]
We are defaulting to the first GPU device for now. Multiple GPU support will come.
