### ISSUE TITLE
No suitable GPU found

### ISSUE THREAD

**Issue by sammy007** [nginnever/zogminer#12]
Sorry for prolly dumb question. I am on ubuntu 16.04 with latest drivers. Headless without xorg (because amd drivers are not compatible with xorg on 16.04)

```
Number of Platforms:1
ERROR: No suitable GPU found! No work will be performed!
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
```

`lsmod`

```
amdkfd                131072  0
amd_iommu_v2           20480  1 amdkfd
amdgpu               1961984  0
ttm                    94208  1 amdgpu
i2c_algo_bit           16384  2 i915_bpo,amdgpu
drm_kms_helper        155648  2 i915_bpo,amdgpu
drm                   364544  5 ttm,i915_bpo,drm_kms_helper,amdgpu
```

I have both internal intel GPU and AMD r9 290. Any hints how to make zogminer find it?

**Comment by omaralvarez** [comment]
Try ```clinfo```, if it cannot find the 290, zogminer won't be able also. Probably a driver issue.

**Comment by sammy007** [comment]
Right, it can't find and I see only Intel GPU there, I installed latest amdgpu driver. No idea what is wrong with it :(

**Comment by omaralvarez** [comment]
Take a look at the driver guides in our readme or wiki pages.

**Comment by awrelll** [comment]
Amdgpupro drivers don't work with 290 series.
