### ISSUE TITLE
memory warning.

### ISSUE THREAD

**Issue by lightningasic** [nginnever/zogminer#13]
/tmp/OCL1776T5.cl:475:30: warning: passing 'const uint8_t *' (aka 'const unsigned  char *') to parameter of type 'void *' discards qualifiers
      memcpy( S->buf + left, in, inlen );

**Comment by omaralvarez** [comment]
We are aware of this warnings, there should not be any problems. But will be fixed soon.

**Comment by nginnever** [comment]
duplicate https://github.com/nginnever/zogminer/issues/10
