### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kruisdraad** [nginnever/zogminer#15]
When running the kernel it wil never reach past 98 iterations and will just return:

Segmentation fault (core dumped)

It will segfault after run 98 each time

dmesg:

[874430.341892] zcash-miner[16109]: segfault at 10001a003f8 ip 00007f04ccd80eee sp 00007fffe7f4ca28 error 4 in libc-2.19.so[7f04ccce9000+1ba000]
[874465.518384] zcash-miner[16120]: segfault at 10001a003f8 ip 00007f517eda4eee sp 00007fff4bd5e4e8 error 4 in libc-2.19.so[7f517ed0d000+1ba000]
[874514.656683] zcash-miner[16149]: segfault at 10001a003f8 ip 00007f50d5448eee sp 00007ffc850ce168 error 4 in libc-2.19.so[7f50d53b1000+1ba000]
[874540.777722] zcash-miner[16225]: segfault at 10001a003f8 ip 00007f21efcfdeee sp 00007fff8199eaa8 error 4 in libc-2.19.so[7f21efc66000+1ba000]
[874591.851730] zcash-miner[16240]: segfault at 10001a003f8 ip 00007f6ac4847eee sp 00007ffd84d67ce8 error 4 in libc-2.19.so[7f6ac47b0000+1ba000]
[874612.700473] zcash-miner[16249]: segfault at 10001a003f8 ip 00007f7a83e17eee sp 00007ffe76e4dc28 error 4 in libc-2.19.so[7f7a83d80000+1ba000]
[874904.007845] zcash-miner[16321]: segfault at 10001a003f8 ip 00007fe5fccc9eee sp 00007fff20a6d4a8 error 4 in libc-2.19.so[7fe5fcc32000+1ba000]
[875149.257718] zcash-miner[16379]: segfault at 10001a003f8 ip 00007f70f945beee sp 00007ffdfd8c41e8 error 4 in libc-2.19.so[7f70f93c4000+1ba000]
[875327.349311] zcash-miner[16390]: segfault at 10001a003f8 ip 00007f03947a4eee sp 00007ffe5129c2e8 error 4 in libc-2.19.so[7f039470d000+1ba000]
[875344.245269] zcash-miner[16400]: segfault at 10001a003f8 ip 00007ff5c21e7eee sp 00007ffc2eb8ca68 error 4 in libc-2.19.so[7ff5c2150000+1ba000]
[875371.569944] zcash-miner[16411]: segfault at 10001a003f8 ip 00007fed485c0eee sp 00007ffe4601ad68 error 4 in libc-2.19.so[7fed48529000+1ba000]

strace:

clock_gettime(CLOCK_MONOTONIC_RAW, {875523, 327565710}) = 0
write(1, "Solutions: 0\n", 13)          = 13
Solutions: 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10001a003f8} ---
+++ killed by SIGSEGV (core dumped) +++

**Comment by omaralvarez** [comment]
I need to further test stability myself and make some changes to the host code. If the error persists I will look into it.

**Comment by kruisdraad** [comment]
i am no coder, but if i can help do let me know.

i have a small farm with GTX1070's which could do tests

**Comment by zogminer** [comment]
Here also Segmentation fault (core dumped) with GTX 960 (although I ran it few times without segfaults).

Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 960
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294770688
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073692672
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of
 GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 4
Kernel run took 415 ms. (9.63855 H/s)
Checking solution 1
Invalid solution: Index tree incorrectly ordered
is valid: 0
Checking solution 2
Invalid solution: Index tree incorrectly ordered
is valid: 0
Checking solution 3
Invalid solution: Index tree incorrectly ordered
is valid: 0
Checking solution 4
[..]
Step: 6...
Step: 7...
Step: 8...
Solutions: 3
Kernel run took 384 ms. (7.8125 H/s)
Checking solution 1
Invalid solution: Index tree incorrectly ordered
is valid: 0
Checking solution 2
Invalid solution: Index tree incorrectly ordered
is valid: 0
Checking solution 3
Invalid solution: Index tree incorrectly ordered
is valid: 0
Valid block found!
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
[..]
Step: 7...
Step: 8...
[OPENCL]:clEnqueueMapBuffer(-36)
Kernel run took 313 ms. (103920 H/s)
Checking solution 1
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 2
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 3
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 4
Invalid solution: duplicate indices
is valid: 0
Checking solution 5
Invalid solution: duplicate indices
is valid: 0
Checking solution 6
Invalid solution: duplicate indices
is valid: 0
Checking solution 7
Invalid solution: duplicate indices
is valid: 0
Checking solution 8
Invalid solution: duplicate indices
is valid: 0
Checking solution 9
Invalid solution: duplicate indices
is valid: 0
Checking solution 10
Invalid solution: duplicate indices
is valid: 0
Checking solution 11
Invalid solution: invalid collision length between StepRows
is valid: 0
Valid block found!
[OPENCL]:clEnqueueWriteBuffer(-5)
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 2
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 3
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 4
Invalid solution: duplicate indices
is valid: 0
Checking solution 5
Invalid solution: duplicate indices
is valid: 0
Checking solution 6
Invalid solution: duplicate indices
is valid: 0
Checking solution 7
Invalid solution: duplicate indices
is valid: 0
Checking solution 8
Invalid solution: duplicate indices
is valid: 0
Checking solution 9
Invalid solution: duplicate indices
is valid: 0
Checking solution 10
Invalid solution: duplicate indices
is valid: 0
Checking solution 11
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 12
Invalid solution: duplicate indices
is valid: 0
Checking solution 13
Invalid solution: duplicate indices
is valid: 0
Checking solution 14
Invalid solution: duplicate indices
is valid: 0
Checking solution 15
Invalid solution: duplicate indices
is valid: 0
Checking solution 16
Invalid solution: duplicate indices
is valid: 0
Checking solution 17
Invalid solution: duplicate indices
is valid: 0
Checking solution 18
Invalid solution: duplicate indices
is valid: 0
Checking solution 19
Invalid solution: duplicate indices
is valid: 0
Checking solution 20
Invalid solution: duplicate indices
is valid: 0
Checking solution 21
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 22
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 23
Invalid solution: invalid collision length between StepRows
is valid: 0
Checking solution 24

**Comment by nginnever** [comment]
that is very odd, it looks like the kernel somehow broke for you and start outputting extremely incorrect solution indices. You can see your number of solutions increasing way beyond theory limits.

**Comment by kruisdraad** [comment]
I do not have such errors, just the segfault ... did you find some debug mode?

**Comment by nginnever** [comment]
fixed in latest commit
