### ISSUE TITLE
errors while working

### ISSUE THREAD

**Issue by rastalr** [nginnever/zogminer#16]
Hello. Thanks for your working.
I have issuses with miner.
1. at start i have this messages

[OPENCL]:/tmp/OCL2139T5.cl:97:14: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
  memcpy(&w, src, sizeof w);
             ^~~
/tmp/OCL2139T5.cl:83:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL2139T5.cl:104:14: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
  memcpy(&w, src, sizeof w);
             ^~~
/tmp/OCL2139T5.cl:83:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL2139T5.cl:351:20: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
    memcpy( block, key, keylen );
                   ^~~
/tmp/OCL2139T5.cl:83:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL2139T5.cl:431:30: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
      memcpy( S->buf + left, in, fill ); /* Fill buffer */
                             ^~
/tmp/OCL2139T5.cl:83:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL2139T5.cl:442:30: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
      memcpy( S->buf + left, in, inlen );
                             ^~
/tmp/OCL2139T5.cl:83:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t n) {
                              ^
/tmp/OCL2139T5.cl:521:26: warning: unknown OpenCL extension 'cl_intel_printf' - ignoring
#pragma OPENCL EXTENSION cl_intel_printf : enable
                         ^
6 warnings generated.

2. while mining gets this messages and 0 hashe on pool.

Solutions: 0
Kernel run took 150 ms. (0 H/s)
Running Equihash solver with nNonce = 000000000000000000000000000000742f00002800000000000000002800002e
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 3
Kernel run took 207 ms. (14.4928 H/s)
Checking solution 1
- Checking solution against target...Found solution satisfying the server target
Solution found; Submitting to zec.suprnova.cc...
  000000000000000000000000000000742f00002800000000000000002800002e
Invalid solution: invalid collision length between StepRows
X[i]   = 0775d80eadc30e8be60c534706692e02c7090691940e07680df2330c6445
X[i+1] = 0022ba0670930da37a002bc0013edc00e09f02b8f90356b8009a880eae8d
[WARN] FAILURE: Miner gave incorrect result!
Checking solution 2
- Checking solution against target... too large.
Checking solution 3
- Checking solution against target... too large.
Running Equihash solver with nNonce = 000000000000000000000000000000752f00002800000000000000002800002e
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...

The system is ubuntu 16.04, gpu rx480 8gb

**Comment by omaralvarez** [comment]
The warnings are ok, don't worry about them. 

About the other messages, 0 H/s in some runs is normal where you don't find solutions.

I have changed hashrate reporting, so it reports an average instead of the result of every run. So you should not see as many 0s.
