### ISSUE TITLE
cannot find -lOpenCL

### ISSUE THREAD

**Issue by mamut321** [nginnever/zogminer#18]
when i put in "./zcutil/build.sh -j$(nproc)" it says "cannot find -lOpenCL" what should i do?

**Comment by omaralvarez** [comment]
This error has to do with the driver installing ```libOpenCL.so``` as ```libOpenCL.so.1```. You can create a symlink:

```
$ sudo ln -s /usr/lib/libOpenCL.so.1 /usr/lib/libOpenCL.so
```

Or for people that do not want to mess with this:

```
$ sudo apt-get install ocl-icd-opencl-dev
```

**Comment by mamut321** [comment]
now when i start program with "./src/zcash-miner" it say "Running the test miner
[OPENCL]:No OpenCL platforms found
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName

Number of Platforms:1
[OPENCL]:No OpenCL platforms found
ERROR: No suitable GPU found! No work will be performed!"
what to do now?

**Comment by omaralvarez** [comment]
You don't have drivers or they are not working properly. Use ```clinfo``` first to check if your cards are being recognized. Look in the closed issues, there are other people that had your same issues.

**Comment by mamut321** [comment]
ok

**Comment by mamut321** [comment]
no it not recognized my gpu..

**Comment by omaralvarez** [comment]
Driver issue for sure. Look at our guides in the wiki:

https://github.com/nginnever/zogminer/wiki

**Comment by mamut321** [comment]
i have nvidia not amd? what to do? that is for amd

**Comment by omaralvarez** [comment]
Drop by gitter. There are people that got nvidia working. I haven't got any nv cards to test.

**Comment by mamut321** [comment]
can you send me link? i can test for you haha

**Comment by omaralvarez** [comment]
https://gitter.im/zogminer/dev
