### ISSUE TITLE
Invalid solution: Index tree incorrectly ordered

### ISSUE THREAD

**Issue by zogminer** [nginnever/zogminer#19]
GTX 960 with https://github.com/nginnever/zogminer/commit/4ae4d2881ede22a83c73802e8396a244b0d5266e
I only get "Invalid solution found!"

Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 960
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294770688
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073692672
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 4
Kernel run took 420 ms. (9.52381 H/s)
Checking solution 1
Invalid solution: Index tree incorrectly ordered
is valid: 0
Invalid solution found!
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 1
Kernel run took 371 ms. (6.10961 H/s)
Checking solution 1
Invalid solution: Index tree incorrectly ordered
is valid: 0
Invalid solution found!
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...

**Comment by omaralvarez** [comment]
Yep, we now and are working on it.

**Comment by nginnever** [comment]
fixed in latest commit
