### ISSUE TITLE
gpusolver.h:36:19: fatal error: CL/cl.h: No such file or directory 

### ISSUE THREAD

**Issue by iCimo** [nginnever/zogminer#2]
got this error compiling on ububntu 16 + amdgpu pro installed

------
In file included from miner.cpp:27:0:
gpusolver.h:36:19: fatal error: CL/cl.h: No such file or directory
compilation terminated.
Makefile:4125: recipe for target 'libbitcoin_server_a-miner.o' failed
make[2]: *** [libbitcoin_server_a-miner.o] Error 1
make[2]: *** Waiting for unfinished jobs....
-----

**Comment by iCimo** [comment]
i thik error come from cuda library that is not available on amd gpu

**Comment by omaralvarez** [comment]
This has to do with your OpenCL installation. Try to install the package:

```sudo apt-get install opencl-headers```

**Comment by iCimo** [comment]
thanks compiler works and build zcash-miner

running i get 
Running the test miner
Init Size: 2097152
Unable to get device_id
Init Size: 2097152
Unable to get device_id
Init Size: 2097152
Unable to get device_id
Init Size: 2097152

investigating on opencl sdk

**Comment by omaralvarez** [comment]
Nice, I will add opencl-headers to the compile intructions. 

Unable to get device_id

Has to do with the driver/OpenCL not being able to see a GPU. You should check that the driver has installed properly. If you are running a headless ubuntu, I think you need to make a dummy xorg for OpenCL to work.

**Comment by iCimo** [comment]
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (2117.7)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 800Mhz
  Address bits:					 64
  Max memory allocation:			 2147483648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 32768
  Global memory size:				 8286142464
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2147483648
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f39eb6568f8
  Name:						 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Vendor:					 GenuineIntel
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 2117.7 (sse2,avx)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (2117.7)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event

**Comment by iCimo** [comment]
i have also tried to install 

sudo apt-get install xserver-xorg-video-dummy
sudo gedit /etc/X11/xorg.conf
 then
Section "Device"
    Identifier  "Configured Video Device"
    Driver      "dummy"
EndSection


Section "Monitor"
    Identifier  "Configured Monitor"
    HorizSync 31.5-48.5
    VertRefresh 50-70
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Monitor     "Configured Monitor"
    Device      "Configured Video Device"
    DefaultDepth 24
    SubSection "Display"
    Depth 24
    Modes "1152x864"
    EndSubSection
EndSection

rebut without any different results except i ear fan start

**Comment by omaralvarez** [comment]
There is your issue.

You only have 1 platform with a CPU, right now in the code I ask for a GPU. I could change it, but the issue has to do with your discrete GPU not being detected.

**Comment by iCimo** [comment]
in other word my driver is not properly installed/configured?

**Comment by omaralvarez** [comment]
Looks like it. I was working with AMDGPU PRO, 16.04 before my PSU went to crap, and it worked. Try reinstalling the driver, now that you have an xorg session.

**Comment by iCimo** [comment]
you suggest install proprietary amd driver ?

http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx

ore opensource and/or somethink else? sdk etc

if I reach we can write down an installation proofed guide

thanks for your parience :)

**Comment by omaralvarez** [comment]
Yes, follow the instructions in that link. But first should be making sure the hardware is getting detected correctly. 

That is why first:

```
sudo lshw -C video
```

To see if your card is working properly.

**Comment by iCimo** [comment]
another step done, problem was UEFI SECURE BOT that inhibit amd 3rdy party load .. without monitor was not easy to debug :)

now I get 

Zcash Miner version v1.0.0-beta2-4b59acc (2016-10-13 16:45:53 +0200)
Running the test miner
Running Equihash solver with nNonce = 0000000000000000000000000000000000000000000000000000000000000000
Init Size: 2097152
Initializing...
Failed to load kernel.

probably because does not exist jet?

**Comment by omaralvarez** [comment]
Yes! You are set!
