### ISSUE TITLE
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by akru** [nginnever/zogminer#22]
```
[OPENCL]:Found suitable OpenCL device [Pitcairn] with 2096103424 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Pitcairn(OpenCL 1.2 AMD-APP (1800.11))
[OPENCL]:Printing program log
[OPENCL]:"/tmp/OCLcdLVuG.cl", line 60: warning: arithmetic on pointer to void or
          function type
      for ( ; n-- ; s1++, s2++) {
                      ^

"/tmp/OCLcdLVuG.cl", line 60: warning: arithmetic on pointer to void or
          function type
      for ( ; n-- ; s1++, s2++) {
                            ^

"/tmp/OCLcdLVuG.cl", line 96: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
    memcpy(&w, src, sizeof w);
               ^

"/tmp/OCLcdLVuG.cl", line 103: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
    memcpy(&w, src, sizeof w);
               ^

"/tmp/OCLcdLVuG.cl", line 195: warning: integer conversion resulted in a
          change of sign
    S->f[1] = -1;
              ^

"/tmp/OCLcdLVuG.cl", line 215: warning: integer conversion resulted in a
          change of sign
    S->f[0] = -1;
              ^

"/tmp/OCLcdLVuG.cl", line 350: warning: argument of type "const void *" is
          incompatible with parameter of type "void *"
      memcpy( block, key, keylen );
                     ^

"/tmp/OCLcdLVuG.cl", line 430: warning: argument of type "const uint8_t *" is
          incompatible with parameter of type "void *"
        memcpy( S->buf + left, in, fill ); /* Fill buffer */
                               ^

"/tmp/OCLcdLVuG.cl", line 441: warning: argument of type "const uint8_t *" is
          incompatible with parameter of type "void *"
        memcpy( S->buf + left, in, inlen );
                               ^

"/tmp/OCLcdLVuG.cl", line 93: warning: function "load32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) load32( const void *src )
                                ^

"/tmp/OCLcdLVuG.cl", line 117: warning: function "load48" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint64_t) load48( const void *src )
                                ^

"/tmp/OCLcdLVuG.cl", line 129: warning: function "store48" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(void) store48( void *dst, uint64_t w )
                            ^

"/tmp/OCLcdLVuG.cl", line 140: warning: function "rotl32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) rotl32( const uint32_t w, const unsigned c )
                                ^

"/tmp/OCLcdLVuG.cl", line 145: warning: function "rotl64" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint64_t) rotl64( const uint64_t w, const unsigned c )
                                ^

"/tmp/OCLcdLVuG.cl", line 150: warning: function "rotr32" was declared but
          never referenced
  BLAKE2_LOCAL_INLINE(uint32_t) rotr32( const uint32_t w, const unsigned c )
                                ^

"/tmp/OCLcdLVuG.cl", line 219: warning: function "blake2b_clear_lastblock" was
          declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_clear_lastblock( blake2b_state *S )
                           ^

"/tmp/OCLcdLVuG.cl", line 237: warning: function
          "blake2b_param_set_digest_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_digest_length( blake2b_param *P, const uint8_t digest_length )
                           ^

"/tmp/OCLcdLVuG.cl", line 243: warning: function "blake2b_param_set_fanout"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_fanout( blake2b_param *P, const uint8_t fanout )
                           ^

"/tmp/OCLcdLVuG.cl", line 249: warning: function "blake2b_param_set_max_depth"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_max_depth( blake2b_param *P, const uint8_t depth )
                           ^

"/tmp/OCLcdLVuG.cl", line 255: warning: function
          "blake2b_param_set_leaf_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_leaf_length( blake2b_param *P, const uint32_t leaf_length )
                           ^

"/tmp/OCLcdLVuG.cl", line 261: warning: function
          "blake2b_param_set_node_offset" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_offset( blake2b_param *P, const uint64_t node_offset )
                           ^

"/tmp/OCLcdLVuG.cl", line 267: warning: function "blake2b_param_set_node_depth"
          was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_depth( blake2b_param *P, const uint8_t node_depth )
                           ^

"/tmp/OCLcdLVuG.cl", line 273: warning: function
          "blake2b_param_set_inner_length" was declared but never referenced
  BLAKE2_LOCAL_INLINE(int) blake2b_param_set_inner_length( blake2b_param *P, const uint8_t inner_length )
                           ^


[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 278 ms. (117799 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
...
Segmentation fault
```

**Comment by gamehubint** [comment]
Im seeing this too on R9 380

**Comment by AgeManning** [comment]
I'm currently working on this. This is because you are using propriety drivers. If you switch to AMDGPU drivers this should rectify the problem. 
I'll continue to try and get this to work for catalyst

**Comment by danwxyz** [comment]
Tahiti cards (Radeon 7970) are not supported by AMDGPU, FWIW.

**Comment by AgeManning** [comment]
Yeah, same with my cards. Hence trying to find a solution for all of us :)

**Comment by danwxyz** [comment]
Cheers! And thanks again!

**Comment by gamehubint** [comment]
Thx - I have 7950, 280, 280x, 290x, 380 and 390 Im testing between.

**Comment by kruisdraad** [comment]
same issue with NVidia:

ZcashMiner:
proof-of-work found
prevHash: 0d84f897d873ed7d04ef36ceab7a5cec4bbbc513f706bf5e426707837d81f94a
    hash: 0cda3ac2684ddbdd52f3d8346ecf1b0d33b1e609a220da3c30f86eb54fcb87ac
  target: 0f0f0f0000000000000000000000000000000000000000000000000000000000
duration: 0
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)

**Comment by kruisdraad** [comment]
Now full start with error:

Kernel run took 146 ms. (10.1052 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:CL ERROR:CL_INVALID_COMMAND_QUEUE
Kernel run took 118 ms. (4781.26 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
ZcashMiner:
proof-of-work found
prevHash: 064872ee852880c2174f3a6ebf294d6117591ab193308c2a2ae49ca07642e5bd
    hash: 03c49703b57fb154ce6ae0684580726bef5fecd4e4555e5e15ed934940db3bb1
  target: 0f0f0f0000000000000000000000000000000000000000000000000000000000
duration: 1
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
Checking solution 5


I've seen this on Ethminers in the past too, and then it was a queuing issue.

**Comment by zogminer** [comment]
Just another example of the same issue:

running https://github.com/nginnever/zogminer/commit/470d4cd6f661a6e723fef09f4deda2f807df47f6
on GTX 960, ubuntu 16.04 with command line:
./src/zcash-miner -G -testnet -user=rpcusername -password=rpcpassword
while zcashd is running as daemon

here and there I see "Valid block found!", but I see no "proof-of-work found".

Everything looks fine, and after ~30 seconds the log gets to this repeating pattern:
[..]
Checking solution 32
Checking solution 33
Checking solution 34
Checking solution 35
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
Checking solution 5
Checking solution 6
Checking solution 7
Checking solution 8
Checking solution 9
Checking solution 10
Checking solution 11
Checking solution 12
Checking solution 13
Checking solution 14
Checking solution 15
Checking solution 16
Checking solution 17
Checking solution 18
Checking solution 19
Checking solution 20
Checking solution 21
Checking solution 22
Checking solution 23
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
[..]

**Comment by dukemc1** [comment]
same here:

[0] Tahiti
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 3134193664
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2202796032
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Tahiti
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 3183476736
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2203582464
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256


[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 57 ms. (574456 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
Checking solution 5
Checking solution 6
Checking solution 7
Checking solution 8
Checking solution 9
Checking solution 10
Checking solution 11
Checking solution 12
Checking solution 13
Checking solution 14
Checking solution 15
Checking solution 16
Checking solution 17
Checking solution 18
Valid block found!
Segmentation fault (core dumped)

**Comment by zogminer** [comment]
This happens after ~30 seconds also with https://github.com/nginnever/zogminer/commit/aa33f140b81a53b03393761763bd448e82636a27

**Comment by omaralvarez** [comment]
Could you guys try last commit?

**Comment by kruisdraad** [comment]
building now, perhaps IRC/Skype is better?

can also give access to mining nodes if that speeds up development

**Comment by omaralvarez** [comment]
I have all issues with my headless miner too. 😜

**Comment by kruisdraad** [comment]
still broken:

Solutions: 2
Kernel run took 129 ms. (12.8094 H/s)
Checking solution 1
Checking solution 2
ZcashMiner:
proof-of-work found
prevHash: 033dcfd734b8faccd577d475df554d0afb5d2308eda830f7af9301190949be8d
    hash: 064872ee852880c2174f3a6ebf294d6117591ab193308c2a2ae49ca07642e5bd
  target: 0f0f0f0000000000000000000000000000000000000000000000000000000000
duration: 3
Valid block found!
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 1
Kernel run took 127 ms. (12.7162 H/s)
Checking solution 1
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 0
Kernel run took 114 ms. (12.4808 H/s)
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 0
Kernel run took 110 ms. (12.2538 H/s)
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 2
Kernel run took 126 ms. (12.3185 H/s)
Checking solution 1
Checking solution 2
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 5
Kernel run took 132 ms. (12.7669 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
Checking solution 5
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 104 ms. (13.3757 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
Checking solution 5
ZcashMiner:
proof-of-work found
prevHash: 064872ee852880c2174f3a6ebf294d6117591ab193308c2a2ae49ca07642e5bd
    hash: 03c49703b57fb154ce6ae0684580726bef5fecd4e4555e5e15ed934940db3bb1
  target: 0f0f0f0000000000000000000000000000000000000000000000000000000000
duration: 1
Valid block found!
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1

**Comment by omaralvarez** [comment]
Ok, but no segfaults. That is good.

**Comment by danwxyz** [comment]
Latest commit crashed my box. (ubuntu 14.04, prop drivers, radeon 7970)

**Comment by omaralvarez** [comment]
With freezing or segfaults?

**Comment by kruisdraad** [comment]
output was from the standalone miner (zcash-miner -G) no segfaults

running the zcashd with mining uption seems to be running without segfaults or out of resources error so far

**Comment by omaralvarez** [comment]
That is weird, since it uses the same host code. I'll keep at it.

**Comment by kruisdraad** [comment]
update: i runs a LOT longer, then segfault:

[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 3
Kernel run took 132 ms. (14.9147 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 1
Kernel run took 130 ms. (14.91 H/s)
Checking solution 1
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 97 ms. (14.907 H/s)
Checking solution 1
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 0 ms. (inf H/s)
Checking solution 1
Invalid solution: invalid collision length between StepRows
Valid block found!
zcashd: /home/miner/zogminer/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/recursive_mutex.hpp:104: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
^CSegmentation fault (core dumped)

**Comment by omaralvarez** [comment]
Nice, that segfault is normal. After kernel is corrupted is expected. But no segfaults until that issue is a good sign. Thanks for the info. I'll keep on trying to fix this.

**Comment by akru** [comment]
Run on *Tahiti* with `strace` have no interesting things and have no valid block too :(

```
nanosleep({1, 0}, NULL)                 = 0
nanosleep({1, 0}, [OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 3 ms. (0 H/s)
 <unfinished ...>
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by omaralvarez** [comment]
Yeah that last commit won't fix ERROR:CL_OUT_OF_RESOURCES issues. That is a kernel problem. I'll be looking into it tomorrow.

**Comment by AgeManning** [comment]
Ok Guys. I've made a branch called catalyst-dev. If you checkout that branch. Let me know if this solves your problems. Its experimental and temporary, let me know if you're cards at least run. 
Cheers

**Comment by kruisdraad** [comment]
@AgeManning but i run NVidia / Cuda / OpenCL? Dont have catalyst installed?

**Comment by AgeManning** [comment]
This fix isn't specific for catalyst. I've changed some parameters which seems to fix this problem for a range of cards. It may work for your nvidia card if you were having this problem. I'm looking into a more robust fix.

**Comment by blacktux88** [comment]
Hi Guys

Same Problem with my AMD Sapphire rx 46.
I have installed the AMD Driver from Homepage.

If there is any workaround let me know

Thanks
Patrick

**Comment by danwxyz** [comment]
```
Checking solution 1
Checking solution 2
[OPENCL]:Running Solver...
Kernel run took 211 ms. (8.71144 H/s)
```

Success! Using catalyst-dev branch.

**Comment by GibsT** [comment]
I have a nvidia 960gtx and it wasn't stable before I switched to catalyst-dev branch. It would crash every 5 minutes or so. I have been running for 38 minutes and still haven't crashed yet. Thats using stratum. I noticed using the test miner I still get ERROR:CL_OUT_OF_RESOURCES after a few seconds.

**Comment by kn0de** [comment]
I used the catalyst-dev branch now instead of ERROR:CL_OUT_OF_RESOURCES I get:

[OPENCL]:Found suitable OpenCL device [Tahiti] with 3183476736 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1800.11))
[OPENCL]:CL ERROR:CL_INVALID_VALUE

**Comment by GibsT** [comment]
Never mind it crashed around 40m of run time. Alot better than 5 though. still gets the ERROR:CL_OUT_OF_RESOURCES error.

**Comment by GibsT** [comment]
With a 960gtx the catalyst branch is more stable for me. I still get ERROR:CL_OUT_OF_RESOURCES errors after a while however.

**Comment by AgeManning** [comment]
@GibsT - I'm aware of the stability issues at the moment. We are working on it. I find it to be more stable without X running (temp work-around). 
@kn0de - I'll have to look into that problem. I may be missing something in OpenCL 1.2 versions. Which card are you running? If I can find some time and a similar card I'll look into it for you. 

Hopefully the changes we are working on will correct most of these issues

**Comment by kn0de** [comment]
I have an r9 280x ... I happen to be running in Ubuntu 15.10 though. If I get a chance i will load 16.04 and try.

**Comment by AgeManning** [comment]
I think that card should work. And use opencl 2.0. Try upgrading opencl and drivers. (Although I should support OpenCL 1.2 also - realistically I don't have the time to test everything and build it all)

**Comment by kn0de** [comment]
Thanks alot for your help. Ill try all those things. I think I had it tweaked for ethereum mining forgot they were older drivers.

**Comment by kn0de** [comment]
Had some trouble with getting OpenCL drivers for 280x on 16.04 --im sure someone knows how (more research)
On my headless server, reinstalled fglrx with these instructions for 15.10:
[http://unix.stackexchange.com/questions/241893/how-to-install-amd-catalyst-15-9-on-ubuntu-15-10](url)
Still on Open CL 1.2: But Got it running :) - Thanks.
[OPENCL]:Running Solver...
Kernel run took 369 ms. (10.8401 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
Checking solution 4
[OPENCL]:Running Solver...
Kernel run took 197 ms. (7.95813 H/s)
Checking solution 1
[OPENCL]:Running Solver...
Kernel run took 197 ms. (8.68951 H/s)
Checking solution 1
Checking solution 2
[OPENCL]:Running Solver...
Kernel run took 196 ms. (7.79264 H/s)
Checking solution 1
[OPENCL]:Running Solver...
Kernel run took 197 ms. (7.24934 H/s)

**Comment by dominiek** [comment]
It was working a bit more stable two days ago, but I am now getting the `ERROR:CL_OUT_OF_RESOURCES` error as well.

On current `master`:

```
$ ./src/zcash-miner -G
Running the test miner
[OPENCL]:Found suitable OpenCL device [GeForce GTX 980 Ti] with 6441730048 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 980 Ti(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Segmentation fault (core dumped)
```

On `catalyst-dev` branch:

```
$ ./src/zcash-miner -G
Running the test miner
[OPENCL]:Found suitable OpenCL device [GeForce GTX 980 Ti] with 6441730048 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 980 Ti(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:ZOGKERNEL Creation failed: clCreateKernel(-46). Bailing.
```

**Comment by ivanmladek** [comment]
On `catalyst-dev` branch:

> ./src/zcash-miner -G
Running the test miner
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1070] with 8507555840 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1070(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:ZOGKERNEL Creation failed: clCreateKernel(-46). Bailing.

**Comment by AgeManning** [comment]
Guys, use the master branch. We've since resolved all these errors.

**Comment by ivanmladek** [comment]
Current `master` still fails. 
./src/zcash-miner -G
Running the test miner

>[OPENCL]:Found suitable OpenCL device [GeForce GTX 1070] with 8507555840 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1070(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Segmentation fault (core dumped)

`clinfo` works.

**Comment by dacox** [comment]
@ivanmladek I'm having exactly the same issue with the 1060 on Ubuntu 16.04. I realize that NVIDIA has spotty OpenCL support but thought I would get further than this

**Comment by isaac60103** [comment]
@ivanmladek  I got the same issue as you. (my device is GeForce GTX 730) Can anyone tell me how to solve this?
