### ISSUE TITLE
Miner not getting OpenCL mode,

### ISSUE THREAD

**Issue by coinnodenl** [nginnever/zogminer#23]
Zcash Miner version v1.0.0-beta2-00e562c (2016-10-24 16:56:16 +0200)
Connecting to stratum server zmine.io:1337
Connected!
Starting miner
ZcashMinerThread started
Subscribed to stratum server
Target set to 0fffffff00000000000000000000000000000000000000000000000000000000
Received new job #1238-1477329994
Authorized worker tmGUdN9CE1wNb7znydNHYiyw8VzqmApnLrp
Running Equihash solver with nNonce = 000000000000000000000000000000006f01000000                                                                                              0000000000000000000000
Generating first list
Round 1:
- Sorting list
- Finding collisions
Round 2:
- Sorting list
- Finding collisions
Round 3:
- Sorting list
- Finding collisions
Round 4:
- Sorting list
- Finding collisions
Round 5:
- Sorting list
- Finding collisions
Round 6:
- Sorting list
- Finding collisions
Round 7:
- Sorting list
- Finding collisions
Round 8:
- Sorting list
^Z

**Comment by omaralvarez** [comment]
Use -G option. I will update the readme.

**Comment by coinnodenl** [comment]
Cheers!
