### ISSUE TITLE
valid block found, but never added to wallet?

### ISSUE THREAD

**Issue by kruisdraad** [nginnever/zogminer#24]
Solutions: 2
Kernel run took 143 ms. (10.2743 H/s)
Checking solution 1
Checking solution 2
ZcashMiner:
proof-of-work found
prevHash: 033dcfd734b8faccd577d475df554d0afb5d2308eda830f7af9301190949be8d
    hash: 064872ee852880c2174f3a6ebf294d6117591ab193308c2a2ae49ca07642e5bd
  target: 0f0f0f0000000000000000000000000000000000000000000000000000000000
duration: 4
Valid block found!

loads of these messages, but the test wallet stays empty?

**Comment by omaralvarez** [comment]
You are using the test miner. Check readme, now solo mining is available and it is run from zcashd.

**Comment by kruisdraad** [comment]
running from zcachd returns in segfaults, last log lines:

Solutions: 0
Kernel run took 128 ms. (10.4757 H/s)
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 1
Kernel run took 145 ms. (10.4388 H/s)
Checking solution 1
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 3
Kernel run took 141 ms. (10.5494 H/s)
Checking solution 1
Checking solution 2
Checking solution 3
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
Solutions: 2
Segmentation fault (core dumped)



running from the solo miner ends up with issue #22

**Comment by omaralvarez** [comment]
We're looking into all this issues.

**Comment by nginnever** [comment]
this should be mostly irrelevant by now
