### ISSUE TITLE
clinfo

### ISSUE THREAD

**Issue by mamut321** [nginnever/zogminer#25]
when i type clinfo i get this error: 
"error while loading shared libraries: libOpenCL.so.1: cannot enable executable stack as shared object requires: Invalid argument" 
what should i do?

**Comment by omaralvarez** [comment]
There are tons of closed issues like this. Do a search, it has to do with driver install. Also check the wiki guide.

**Comment by mamut321** [comment]
i dont find fix for that? i reinstal driver and cuda and openCl and nothing help

**Comment by kruisdraad** [comment]
i dont think @omaralvarez will help you with driver support, so as he said ... go look in the loads of fora already explaining this issue.

**Comment by mamut321** [comment]
i have look nothing help

**Comment by omaralvarez** [comment]
I'm sorry but I cannot help you with that now. When the miner is more stable I'll try to help you.

**Comment by mamut321** [comment]
Ok then nothing
