### ISSUE TITLE
Multiple GPU mining

### ISSUE THREAD

**Issue by kruisdraad** [nginnever/zogminer#26]
So far you can list and mine with a specific GPU, but does it allow to select up to 6 or do you need to run 6 instances (and does that work?)

**Comment by omaralvarez** [comment]
For now we have not had time to implement multi-GPU. We're on it.

**Comment by sigwo** [comment]
Any word on multi-gpu support?

**Comment by AgeManning** [comment]
See multi-gpu branch. 
Use the flag allgpu=1 with zcashd. 
Its currently under dev

**Comment by sigwo** [comment]
compiled and testing now.

**Comment by sigwo** [comment]
I get this:
```
./src/zcash-miner -G -stratum="stratum+tcp://zec-eu.suprnova.cc:2142" -user=sigwo.SIGFARM4 -password=x -allgpu=1
[OPENCL]:Found suitable OpenCL device [Ellesmere] with 8544440320 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Ellesmere(OpenCL 1.2 AMD-APP (2117.7))
[OPENCL]:CL ERROR:CL_INVALID_VALUE
```

**Comment by omaralvarez** [comment]
Probably due to define flag. Try running from ```cd src```.

**Comment by sigwo** [comment]
Yup, we need to update README.md i think. it runs, but definitely not at proper speed. only running what looks to be 22h/s with 6x RX 480 8GB that run 40 sol/s per GPU (~240 sol/s total) with other (right now, less trustworthy) GPU software.

**Comment by gitcsec** [comment]
Where can we find the mult-gpu branch?

**Comment by nginnever** [comment]
https://github.com/nginnever/zcash multi-solo branch for now. I will merge to master shortly
