### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Sergiustkn** [nginnever/zogminer#28]
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
......
Step: 8...
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Kernel run took 123 ms. (62361 H/s)
Checking solution 1
......
Checking solution 28
Invalid solution: invalid collision length between StepRows
Valid block found!
[OPENCL]:Running Solver...
Step: 1...
Step: 2...
......
Step: 8...

^C^M^Z
freezing and not action !!!! 

sudo dpkg -l fglrx fglrx-core fglrx-amdcccle fglrx-dev
||/ Name            Version           Architecture  Description
+++-===============-=================-=============-=====================================================
ii  fglrx           2:15.302-0ubuntu1 amd64         Video driver for the AMD graphics accelerators
ii  fglrx-amdcccle  2:15.302-0ubuntu1 amd64         Catalyst Control Center for the AMD graphics accelera
ii  fglrx-core      2:15.302-0ubuntu1 amd64         Minimal video driver for the AMD graphics accelerator
ii  fglrx-dev       2:15.302-0ubuntu1 amd64         Video driver for the AMD graphics accelerators (devel

**Comment by omaralvarez** [comment]
Try latest version. We are working on fixing this issues.

**Comment by Sergiustkn** [comment]
nothing changed, working for 10..15 solver and get freezing, with no any error on display

**Comment by omaralvarez** [comment]
Noted, I will keep on trying to find the issue.

**Comment by gitcsec** [comment]
Hi, same issue here. Machined freeze aftend nothing displayed. Had to restart it.

  Device #0 (0) name:     Hawaii
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (2117.7)
    Driver version:         2117.7 (VM) - Crimson

**Comment by Sergiustkn** [comment]
without effect...
https://github.com/nginnever/zogminer/commit/ab39288c3d7010567b38afcefecd56136ae480a8

**Comment by gitcsec** [comment]
I just tried the last commit and after some time mining, it didn't froze but it stopped mining and the system because unusable and had to restart it.

**Comment by nginnever** [comment]
This should be fixed by now
