### ISSUE TITLE
"Failed to load kernel." with README.md's instructions

### ISSUE THREAD

**Issue by solardiz** [nginnever/zogminer#3]
README.md says:

```
$ ./src/zcash-miner
```

but with the current location of OpenCL kernels (in "src" and "tests"), this should probably be:

```
$ cd src
$ ./zcash-miner -debug
```

Then the miner starts and pretends to work, but GPU utilization is reported by aticonfig as 0% and its clock rate barely increases from what it is at idle. "debug.log" is getting different nonces logged to it, but no info on any solutions. I guess this isn't a complete miner yet?

**Comment by omaralvarez** [comment]
Nop, we haven't commited the full kernel yet. This is a WIP.

The kernel load issue will be fixed, and there will be no need to run it from src.

**Comment by solardiz** [comment]
OK, thanks. As a judge in the Challenge, I needed to know the current submissions' relative status as of today, as having the "substance" already in by/on October 14 (or if not, then the sooner the better) is listed among judging criteria.

**Comment by omaralvarez** [comment]
Right now everything is in place but the kernel, that we will commit soon.

**Comment by nginnever** [comment]
Thank you for the response omaralvarez, I have been incredibly swamped this weekend.

Thanks for taking a look solardiz! Sorry I have not commit the kernel so there should be no gpu usage atm aside from some buffer loading from the host. I will be committing that shortly but yes we are a GPU opencl build.

Cheers!

**Comment by zminer** [comment]
Hello is the miner working properly I am pretty new to ubuntu so If any bugs can I try to mine with this on testnet

**Comment by AgeManning** [comment]
@zminer - The miner is not finished yet and currently doesn't run on the testnet. Please follow this thread: 
https://forum.z.cash/t/zogminer-open-source-gpu-miner/2152/102

@nginnever will update the progress and let everyone know when they can start building it.

**Comment by omaralvarez** [comment]
Fixed kernel load issue in:

cc1fef4f70b8e129eea2afd0ee875f2fccdd1977
