### ISSUE TITLE
ERROR: No suitable GPU found! No work will be performed!

### ISSUE THREAD

**Issue by johnnagro** [nginnever/zogminer#31]
```
➜  zogminer git:(master) ./src/zcash-miner -listdevices
Number of Platforms:1
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1060 3GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 3159687168
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 789921792
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

➜  zogminer git:(master) ./src/zcash-miner -G          
Running the test miner
ERROR: No suitable GPU found! No work will be performed!
^C
```

**Comment by nginnever** [comment]
nividia is not supported and does not run well with zogminer's kernel. Also this looks like you have no suitable opencl devices installed

**Comment by johnnagro** [comment]
@nginnever what is a "suitable opencl device" ? it you're building against openCL why is only a particular card type supported?

**Comment by nginnever** [comment]
the kernel is built with 64 wavefronts not 32 warps and other optimizations. The kernel "should" run on nvidia because it is opencl standard. But likely it will crash. You need a cuda implementation to utilize nvidia. This is open source
