### ISSUE TITLE
[OPENCL]:CL ERROR:NVIDIA: ILLEGAL READ OR WRITE TO A BUFFER

### ISSUE THREAD

**Issue by zogminer** [nginnever/zogminer#32]
HEAD:
https://github.com/nginnever/zogminer/commit/56d0e001322b37cd4ef1f6df568bed0e5a12f64a

Running the test miner
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
is valid: 1
Valid solution found!
Kernel run took 357 ms. (5.41385 H/s)
is valid: 1
Valid solution found!
[..]
is valid: 0
Invalid solution found!
[OPENCL]:CL ERROR:NVIDIA: ILLEGAL READ OR WRITE TO A BUFFER
Invalid solution: invalid collision length between StepRows
is valid: 0
Invalid solution found!
[OPENCL]:CL ERROR:NVIDIA: ILLEGAL READ OR WRITE TO A BUFFER
Kernel run took 0 ms. (inf H/s)
Invalid solution: invalid collision length between StepRows
is valid: 0

**Comment by maurycyp** [comment]
I'm also seeing this error on `master` ( 2cc8991a4b8fdf960e4f262d7d499f7c800f49f5 ).
:(

**Comment by maurycyp** [comment]
Btw, I'm on Ubuntu with an Nvidia card.

**Comment by skrew** [comment]
I can confirm this problem too

**Comment by gnu-user** [comment]
I can also confirm this issue using the same GPU, ubuntu 16.04.

**Comment by nginnever** [comment]
zogminer does not run well with nvidia. we dont have any plans of fixing this
