### ISSUE TITLE
immediate segfault + [OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by zogminer** [nginnever/zogminer#35]
with master HEAD:
https://github.com/nginnever/zogminer/commit/3501698a206470da7e427e59d0227f00e27365dc

./src/zcash-miner -G
Running the test miner
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

Solving nonce 0000000000000000000000000000000000000000000000000000000000000000
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Solutions: 486565743
Segmentation fault (core dumped)

**Comment by salyh** [comment]
same here with 3501698a206470da7e427e59d0227f00e27365dc and i get also a ``/opt/nvidia/cuda/lib64/libOpenCL.so.1: no version information available``

/src/zcash-miner: /opt/nvidia/cuda/lib64/libOpenCL.so.1: no version information available (required by ./src/zcash-miner)
./src/zcash-miner: /opt/nvidia/cuda/lib64/libOpenCL.so.1: no version information available (required by ./src/zcash-miner)
Running the test miner
[OPENCL]:Found suitable OpenCL device [GRID K520] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GRID K520(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

Solving nonce 0000000000000000000000000000000000000000000000000000000000000000
[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
Solutions: 1920234285
Segmentation fault (core dumped)

**Comment by salyh** [comment]
I get the same error also with earlier commits. Kernel is 4.4.19-29.55.amzn1.x86_64 with libnvidia-opencl.so.352.99.

**Comment by xShirase** [comment]
nvidia-370 drivers Ubuntu 16.04 x64
```
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1080] with 8500346880 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1080(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES
```

**Comment by durasj** [comment]
Same here with Tesla K80 (12GB RAM). Looks like an Nvidia-related problem. I am running Ubuntu 14.04 x64. Here is Debugging info:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./src/zcash-miner -G'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f71da0b2b47 in GPUSolver::GPUSolve200_9(unsigned char*, unsigned long, unsigned long, std::function<bool (std::vector<unsigned char, std::allocator<unsigned char> >)>, std::function<bool (GPUSolverCancelCheck)>, crypto_generichash_blake2b_state) (this=this@entry=0x7f71da8c7a00, header=header@entry=0x7f71db3c4d70 "\004",
    header_len=header_len@entry=108, nonce=nonce@entry=0, validBlock=..., cancelled=..., base_state=...) at libzogminer/gpusolver.cpp:212
212                     index_vector[i] = indices->values[s-1][i];
```

Thank you

**Comment by dkronst** [comment]
Same here (GeForce GTX 970):

[OPENCL]:Using device: GeForce GTX 970(OpenCL 1.2 CUDA)
[New Thread 0x7ffff3e77700 (LWP 7261)]
[New Thread 0x7fffeb3ff700 (LWP 7262)]
[New Thread 0x7fffea9b3700 (LWP 7263)]
[New Thread 0x7fffea1b2700 (LWP 7264)]
[New Thread 0x7fffe99b1700 (LWP 7265)]
[New Thread 0x7fffe91b0700 (LWP 7266)]
[New Thread 0x7fffe89af700 (LWP 7267)]
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:CL ERROR:CL_OUT_OF_RESOURCES

Thread 1 "zcash-miner" received signal SIGSEGV, Segmentation fault.
0x00005555557a9bd8 in GPUSolver::GPUSolve200_9(unsigned char*, unsigned long, unsigned long, std::function<bool (std::vector<unsigned char, std::allocator<unsigned char> >)>, std::function<bool (GPUSolverCancelCheck)>, crypto_generichash_blake2b_state) (
    this=this@entry=0x555555aa64a0, header=header@entry=0x55555650aeb0 "\004", header_len=header_len@entry=108, nonce=nonce@entry=0, 
    validBlock=..., cancelled=..., base_state=...) at libzogminer/gpusolver.cpp:212
212                     index_vector[i] = indices->values[s-1][i];

**Comment by nginnever** [comment]
zogminer does not support nvidia
