### ISSUE TITLE
/usr/bin/ld: cannot find -lOpenCL at build stage

### ISSUE THREAD

**Issue by pshenmic** [nginnever/zogminer#4]
Having trouble with building zogminer on Debian 8. Here is the ./build.sh output:

libtool: link: /home/debian/miners/zogminer/depends/x86_64-unknown-linux-gnu/native/bin/ccache g++ -m64 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o zcashd zcashd-bitcoind.o -fopenmp  -L/home/debian/miners/zogminer/depends/x86_64-unknown-linux-gnu/lib libbitcoin_server.a libbitcoin_common.a univalue/libbitcoin_univalue.a libbitcoin_util.a ./leveldb/libleveldb.a ./leveldb/libmemenv.a secp256k1/.libs/libsecp256k1.a libbitcoin_wallet.a -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt -ldb_cxx-5.3 -lssl -ldl -lminiupnpc libzcash.a crypto/libbitcoin_crypto.a -lsnark /home/debian/miners/zogminer/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a /home/debian/miners/zogminer/depends/x86_64-unknown-linux-gnu/lib/libgmp.a -lboost_system-mt -lcrypto /home/debian/miners/zogminer/depends/x86_64-unknown-linux-gnu/lib/libsodium.a libzogminer.a -lOpenCL -lanl -fopenmp -pthread
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
Makefile:3154: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: Leaving directory '/home/debian/miners/zogminer/src'
Makefile:7496: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/debian/miners/zogminer/src'
Makefile:633: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Just installed opencl(opencl is working on claymore dualminer), then trying to build.
Additionally, I copied all libraries from /opt/AMDAPPSDK-3.0/ to /usr/lib/OpenCL/vendors/amd (both x86 and amd) and also added their references in /etc/ld.so.conf.d

**Comment by omaralvarez** [comment]
This error has to do with the driver installing the ```libOpenCL.so``` as ```libOpenCL.so.1". You can create a symlink:

```
$ sudo ln -s /usr/lib/libOpenCL.so.1 libOpenCL.so
```

Or for people that do not want to mess with this:

```
$ sudo apt-get install ocl-icd-opencl-dev
```

**Comment by pshenmic** [comment]
I successfully compiled master. Howewever, the miner is unexpectedly slow. In average, kernel run took 4834 ms. (0.206868 H/s) and pretty hot(70 c). R9 390x, Debian8 amd64 Isn't the solve time should be less?

**Comment by omaralvarez** [comment]
Right now you are not running a real solver. Disregard results, when the kernel is ready we will let you guys know.
