### ISSUE TITLE
OPENCL error when starting zcash-miner

### ISSUE THREAD

**Issue by chey** [nginnever/zogminer#41]
[OPENCL]:Found suitable OpenCL device [Tahiti] with 3179282432 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1800.11))
[OPENCL]:Printing program log
[OPENCL]:"/tmp/OCLRQQ3gr.cl", line 287: warning: integer conversion resulted in a
          change of sign
          v[14] ^= -1;
                   ^

**Comment by strusty** [comment]
confirm exact problem with exact output

**Comment by strusty** [comment]
this is apparently non-fatal, after 30sec or so, it starts up OK

**Comment by AgeManning** [comment]
This is just a warning because of the catalyst drivers. This is fine. It should run soon after this warning.
