### ISSUE TITLE
build against fglrx yields  /usr/bin/ld: cannot find -lOpenCL

### ISSUE THREAD

**Issue by strusty** [nginnever/zogminer#46]
clinfo shows devices fine.  

build goes OK until dies with /usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status

not using amdgpu-pro due to headless remote system mining ETH on R9 390s.  

is there a workaround for this, as installation of libopencl1-amdgpu-pro_16.40-348864_amd64.deb brings no relief?

**Comment by omaralvarez** [comment]
This error has to do with the driver installing ```libOpenCL.so``` as ```libOpenCL.so.1```. You can create a symlink:

```
$ sudo ln -s /usr/lib/libOpenCL.so.1 /usr/lib/libOpenCL.so
```

Or for people that do not want to mess with this:

```
$ sudo apt-get install ocl-icd-opencl-dev
```
