### ISSUE TITLE
hashrate quickly drops

### ISSUE THREAD

**Issue by nerdralph** [nginnever/zogminer#48]
Ubuntu 14.04, fglrx, Zcash Miner version v1.0.0-beta2-331ea50 (latest as of 2016-10-30)

./src/zcash-miner -G
Running the test miner
[OPENCL]:Found suitable OpenCL device [Tonga] with 4108320768 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tonga(OpenCL 2.0 AMD-APP (1800.11))
[OPENCL]:Printing program log
[OPENCL]:"/tmp/OCLmHpXNE.cl", line 287: warning: integer conversion resulted in a
          change of sign
          v[14] ^= -1;
                   ^

Kernel run took 83 ms. (35.5581 H/s)
Kernel run took 76 ms. (31.5199 H/s)
Kernel run took 75 ms. (25.4637 H/s)
Kernel run took 85 ms. (23.5684 H/s)
Kernel run took 81 ms. (21.3239 H/s)
Kernel run took 76 ms. (20.5733 H/s)
Kernel run took 82 ms. (21.8986 H/s)
Kernel run took 78 ms. (22.1938 H/s)
Kernel run took 97 ms. (22.2265 H/s)
Kernel run took 87 ms. (21.4204 H/s)
Kernel run took 81 ms. (22.3411 H/s)
Kernel run took 82 ms. (22.4499 H/s)
Kernel run took 73 ms. (23.3142 H/s)
Kernel run took 62 ms. (21.6489 H/s)
Kernel run took 60 ms. (20.2057 H/s)
Kernel run took 61 ms. (18.9428 H/s)
Kernel run took 60 ms. (17.8285 H/s)
Kernel run took 60 ms. (16.838 H/s)
Kernel run took 60 ms. (15.9518 H/s)
Kernel run took 61 ms. (15.1542 H/s)
Kernel run took 60 ms. (14.4326 H/s)
Kernel run took 60 ms. (13.7766 H/s)
Kernel run took 60 ms. (13.1776 H/s)
Kernel run took 60 ms. (12.6285 H/s)
Kernel run took 61 ms. (12.1234 H/s)
Kernel run took 61 ms. (11.6571 H/s)
Kernel run took 61 ms. (11.2254 H/s)
Kernel run took 60 ms. (10.8245 H/s)
Kernel run took 60 ms. (10.4512 H/s)

**Comment by coreymason** [comment]
You have to connect to a pool

**Comment by nginnever** [comment]
Our profiler currently isn't averaging the times correctly. I noticed this too awhile back

**Comment by gitcsec** [comment]
Looks like I experience the same behaviour
$ ./src/zcash-miner -G -S=0ratum="stratum+tcp://zec.suprnova.cc:2142" -user=user.worker -password=password -allgpu=1
Running the test miner
[OPENCL]:Found suitable OpenCL device [Hawaii] with 4216999936 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Hawaii(OpenCL 1.2 AMD-APP (2117.7))
[OPENCL]:Printing program log
[OPENCL]:
Kernel run took 59 ms. (56.8957 H/s)
Kernel run took 53 ms. (47.7825 H/s)
Kernel run took 49 ms. (38.5096 H/s)
Kernel run took 59 ms. (35.4919 H/s)
Kernel run took 55 ms. (32.0847 H/s)
Kernel run took 53 ms. (30.7731 H/s)
Kernel run took 57 ms. (32.53 H/s)
Kernel run took 51 ms. (32.8596 H/s)
Kernel run took 71 ms. (32.8501 H/s)
Kernel run took 62 ms. (31.5258 H/s)
Kernel run took 58 ms. (32.6808 H/s)
Kernel run took 68 ms. (32.5254 H/s)
Kernel run took 60 ms. (33.1416 H/s)
Kernel run took 52 ms. (30.7743 H/s)
Kernel run took 52 ms. (28.7227 H/s)
Kernel run took 52 ms. (26.9275 H/s)
Kernel run took 50 ms. (25.3435 H/s)
Kernel run took 51 ms. (23.9356 H/s)
Kernel run took 50 ms. (22.6758 H/s)
Kernel run took 51 ms. (21.542 H/s)
Kernel run took 50 ms. (20.5162 H/s)
Kernel run took 50 ms. (19.5836 H/s)
Kernel run took 50 ms. (18.7322 H/s)

**Comment by nginnever** [comment]
fixed in master
