### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by coreymason** [nginnever/zogminer#49]
I'm on ubuntu 16.04 (64bit) running an rx480 with custom rom (and the master repo as of 12 hours or so ago) but got a segmentation fault after about 20 minutes i think. I started it with
`./zcash-miner -G -genproclimit=2 -stratum="stratum+tcp://zec.suprnova.cc:2142" -user=username -password=password`
Here are the last few print statements of that's of any help...
```
Invalid solution: invalid collision length between StepRows
Invalid solution: invalid collision length between StepRows
Kernel run took 85 ms. (22.3549 H/s)
Kernel run took 80 ms. (22.5525 H/s)
Kernel run took 83 ms. (22.3568 H/s)
Kernel run took 82 ms. (22.5546 H/s)
Kernel run took 81 ms. (22.3511 H/s)
Kernel run took 83 ms. (22.5533 H/s)
Kernel run took 83 ms. (22.3505 H/s)
Kernel run took 80 ms. (22.5577 H/s)
Kernel run took 84 ms. (22.346 H/s)
Kernel run took 86 ms. (22.5507 H/s)
Kernel run took 82 ms. (22.343 H/s)
Kernel run took 87 ms. (22.556 H/s)
Segmentation fault (core dumped)
```

Any ideas? I'll start running it again to see if it consistently seg faults again

**Comment by nginnever** [comment]
zogminer does not support genproclimit=2 yet. You need to run two zogminer instances next to each other.

**Comment by coreymason** [comment]
Ah, okay. So "unofficially" I need two terminals both running that command or was I doing it correctly (aside from the lack of support)?
