### ISSUE TITLE
error: 'long long' type is not supported

### ISSUE THREAD

**Issue by zogminer** [nginnever/zogminer#5]
Ubuntu 16.04 with Nvidia GTX 960.
I just compiled the head https://github.com/nginnever/zogminer/commit/c2341ba4ab98c178d2850e67e7d7bae129f5f329
compilation successful.
When trying to run, I get:

Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 960
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294770688
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073692672
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:<kernel>:69:5: error: 'long long' type is not supported
    0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL,
    ^
<kernel>:69:28: error: 'long long' type is not supported
    0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL,
                           ^
<kernel>:70:5: error: 'long long' type is not supported
    0x3c6ef372fe94f82bULL, 0xa54ff53a5f1d36f1ULL,
    ^
<kernel>:70:28: error: 'long long' type is not supported
    0x3c6ef372fe94f82bULL, 0xa54ff53a5f1d36f1ULL,
                           ^
<kernel>:71:5: error: 'long long' type is not supported
    0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL,
    ^
<kernel>:71:28: error: 'long long' type is not supported
    0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL,
                           ^
<kernel>:72:5: error: 'long long' type is not supported
    0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL
    ^
<kernel>:72:28: error: 'long long' type is not supported
    0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL
                           ^
<kernel>:112:16: warning: passing 'const __attribute__((address_space(16776963))) void *__attribute__((address_space(16776963)))' to parameter of type '__attribute__((address_space(16776963))) void *' discards qualifiers
    memcpy(&w, src, sizeof(w));
               ^~~
<kernel>:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^
<kernel>:184:24: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type 
        m[i] = load64( block + i * sizeof( m[i] ) );
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
<kernel>:107:29: note: passing argument to parameter 'src' here
ulong load64( __const void *src )
                            ^
<kernel>:252:36: warning: passing 'const __attribute__((address_space(16776963))) uchar *__attribute__((address_space(16776963)))' (aka 'const __attribute__((address_space(16776963))) unsigned char *__attribute__((address_space(16776963)))') to parameter of type '__attribute__((address_space(16776963))) void *' discards qualifiers
            memcpy( S->buf + left, in, fill ); /* Fill buffer */
                                   ^~
<kernel>:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^
<kernel>:267:36: warning: passing 'const __attribute__((address_space(16776963))) uchar *__attribute__((address_space(16776963)))' (aka 'const __attribute__((address_space(16776963))) unsigned char *__attribute__((address_space(16776963)))') to parameter of type '__attribute__((address_space(16776963))) void *' discards qualifiers
            memcpy( S->buf + left, in, inlen );
                                   ^~
<kernel>:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^

[OPENCL]:clEnqueueWriteBuffer(-38)
Kernel run took 0 ms. (inf H/s)
[OPENCL]:clEnqueueWriteBuffer(-38)
Kernel run took 0 ms. (inf H/s)
[OPENCL]:clEnqueueWriteBuffer(-38)
Kernel run took 0 ms. (inf H/s)

**Comment by omaralvarez** [comment]
I think it has to do with the OpenCL Nvidia compiler version, that does not support the same types as AMD. For now don't worry about this, the solver is not yet committed.

**Comment by twoletters** [comment]
I run into the exact same problem on the same environment (GTX 960 and Ubuntu 16.04).

**Comment by zogminer** [comment]
According to https://devtalk.nvidia.com/default/topic/472856/-39-long-long-39-type-is-not-supported/ 
long long is C99 standard, which is NOT a part of OpenCL, but the "long" type of OpenCL satisfies the requirements for "long long" in C99, so it is possible to use it.

It means just a typedef in the correct place, and voila.

**Comment by omaralvarez** [comment]
Yup, thanks for the research. I did not change it, because we were going to scrap the full kernel. The new kernel I think should not have issues. Although if it has them I will be on point.

**Comment by zogminer** [comment]
Problem gone with the new kernel on Nvidia GTX 960. Confirmed.
