### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by nerdralph** [nginnever/zogminer#50]
./src/zcash-miner -G -stratum="stratum+tcp://us-east1.zcash.miningpoolhub.com:20570" -user=test -password=x
[OPENCL]:Found suitable OpenCL device [Tonga] with 4108320768 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tonga(OpenCL 2.0 AMD-APP (1800.11))
terminate called without an active exception
Aborted (core dumped)

Test mode works OK, aside from #48 

built with gcc 6.1.1, will try with 4.8.4
edit: same result with gcc 4.8.4

**Comment by duxr** [comment]
Same problem here (builds on Ubuntu 14.04 w/AMDGPU-PRO fresh install)

**Comment by glambeth** [comment]
Same problem here as well (Ubuntu 16.04 & AMDGPU-PRO 16.30)

**Comment by sobsidian** [comment]
I'm having the same issue.

Linux deluzion.net 4.7.9-200.fc24.x86_64 #1 SMP Thu Oct 20 14:26:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

glibc-2.23.1-10.fc24.x86_64
opencl-headers-1.2-9.fc24
gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC)

**Comment by omaralvarez** [comment]
Does flypool work for you guys? Just want to know because, it would give us hints for debugging the issue.

**Comment by nerdralph** [comment]
Interesting.  For eth mining, pools accept usernames without a rig fine.
Nevertheless, I supplied a rig name and can connect to mph, but get "Checking solution against target... too large" errors.
I tried flypool, and get the same "too large" errors.

**Comment by nerdralph** [comment]
as per @omaralvarez, error is due to lack of worker name, which causes stratum auth failure.
