### ISSUE TITLE
Tahiti does not hash

### ISSUE THREAD

**Issue by gpushack** [nginnever/zogminer#53]
## Tahiti

slow time resulting in 0 hash: 
I get 2800ms 0's instaead of 110ms 0's
http://i.imgur.com/LLRoFsI.png

**Comment by nginnever** [comment]
see nvidia not supported

**Comment by gpushack** [comment]
Tahiti is HD 7950 , not nvidia

**Comment by gpushack** [comment]
Tahiti is also AMD R9 280, AMD R9 280X
