### ISSUE TITLE
Is this intended to be submitted to the ZCash Miners Contest?

### ISSUE THREAD

**Issue by gnu-user** [nginnever/zogminer#6]
Is this project intended to be submitted to the ZCash Miners contest (http://zcashminers.org)? If so is it expected to be completed in time for launch?

If there is still a lot that needs to be completed I may know some developers including myself that would be interested in collaborating on the project so that it can be submitted to the contest and completed before the launch.

**Comment by nginnever** [comment]
Thanks for contacting us. We are submitted to the open source contest but at this point winning that or having a chance is not in my top priority. I'm working on writing a kernel with a pattern described [here](https://github.com/xenoncat/equihash-xenon/blob/master/notes/algorithm%20description.pdf). Credit to xenoncat and tromp for working on that method of solution. 

Feel free to drop by the #dev channel in gitter and let me know how you think you could contribute. I am on a hack -a-thon to build the kernel atm but could use help dropping it into the zcashd implementation and review of the kernel as well if you feel comfortable.

**Comment by omaralvarez** [comment]
Hey, all help is welcome. We are about to commit a solver, I will be testing it and integrating it in str4d standalone solver.
