### ISSUE TITLE
Get EhSolverCancelledException, then core dump.

### ISSUE THREAD

**Issue by dan-da** [nginnever/zogminer#60]
I'm getting a crash. EhSolverCancelledException. then core dump. I tried with 4 different GPU devices. two are tahiti, two are pitcairn.  Also tried two different pools.  always same result.

---------

./zcash-miner -debug -printtoconsole -S=1 -stratum="stratum+tcp://zec-us-west1.nanopool.org:6666" -user= -password=foo
Zcash Miner version v1.0.0-beta2-ad6750f (2016-10-31 10:17:41 +0100)
Connecting to stratum server zec-us-west1.nanopool.org:6666
Connected!
Starting miner
ZcashMinerThread started
Subscribed to stratum server
Target set to 00147ae100000000000000000000000000000000000000000000000000000000
Authorized worker .gpu0
Received new job #1477944221
Running Equihash solver with nNonce = 000000000000000000000000000000007cf3233cf907e7d80000000000000e34
Generating first list
Round 1:
- Sorting list
- Finding collisions
Round 2:
- Sorting list
- Finding collisions
Round 3:
- Sorting list
- Finding collisions
Round 4:
- Sorting list
- Finding collisions
Round 5:
- Sorting list
- Finding collisions
Round 6:
- Sorting list
- Finding collisions
Received new job #1477944252
terminate called after throwing an instance of 'EhSolverCancelledException'
what(): Equihash solver was cancelled
Aborted (core dumped)

---------

$ ./zcash-miner -listdevices
Number of Platforms:1
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Pitcairn
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 2112186240
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1402257408
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Pitcairn
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 2112186240
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1402257408
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[2] Tahiti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 3183273856
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2203385856
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[3] Tahiti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 3183306624
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2205597696
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

**Comment by nginnever** [comment]
You are running the cpu solver. Add -G flag for gpu

./zcash-miner -G -debug -printtoconsole -S=1 -stratum="stratum+tcp://zec-us-west1.nanopool.org:6666" -user= -password=foo

**Comment by dan-da** [comment]
thx.  but it only seems to be in benchmarking mode when I do that.

-------

$ ./zcash-miner -G -stratum=stratum+tcp://zec-us-west1.nanopool.org:6666 -user=addr.gpu0 -password=x
[OPENCL]:Found suitable OpenCL device [Pitcairn] with 2112186240 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Pitcairn(OpenCL 1.2 AMD-APP (1912.5))
[OPENCL]:Printing program log
[OPENCL]:"/tmp/OCL31806T4.cl", line 288: warning: integer conversion resulted in a
          change of sign
          v[14] ^= -1;
                   ^


Kernel run took 136 ms. (12.1901 H/s)
Kernel run took 133 ms. (11.1828 H/s)
Kernel run took 159 ms. (12.1283 H/s)
Kernel run took 147 ms. (13.4232 H/s)

**Comment by dan-da** [comment]
If I run it with -debug, there is some more info:

[OPENCL]:Found suitable OpenCL device [Pitcairn] with 2112186240 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1912.5))
Subscribed to stratum server
Target set to 00147ae100000000000000000000000000000000000000000000000000000000
Authorized worker txxxx.gpu0
Received new job #1477945675
[OPENCL]:Printing program log
[OPENCL]:"/tmp/OCL32723T4.cl", line 288: warning: integer conversion resulted in a
          change of sign
          v[14] ^= -1;
                   ^


Received new job #1477945705
Running Equihash solver with nNonce = 00000000000000000000000000000000024170c2f390a1730000000000000d00
- Checking solution against target... too large.
- Checking solution against target... too large.
Running Equihash solver with nNonce = 00000000000000000000000000000001024170c2f390a1730000000000000d00
Running Equihash solver with nNonce = 00000000000000000000000000000002024170c2f390a1730000000000000d00
- Checking solution against target... too large.
- Checking solution against target... too large.
- Checking solution against target... too large.
....
