### ISSUE TITLE
AMD RX 480

### ISSUE THREAD

**Issue by ddobreff** [nginnever/zogminer#74]
Hello
[ 2698.254894] amdgpu 0000:01:00.0: GPU pci config reset
[ 3064.147649] zcash-miner[20767]: segfault at 110 ip 00007eff2908c034 sp 00007fff3e112938 error 4 in libdrm_amdgpu.so.1.0.0[7eff29087000+b000]

I have linked /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0 to /usr/lib/x86_64-linux-gnu on Ubuntu 16.04 but still segfaults....Any help appreciated

**Comment by ddobreff** [comment]
Fixed, had nvidia drivers installed so everything is fine now.
Close please.
P.S. I receive 20H/s is that S/s or H/s ?

**Comment by omaralvarez** [comment]
I'm glad everything is working now, S/s.
