### ISSUE TITLE
AMD 480 GPU, Ubuntu 16.04. hung up .

### ISSUE THREAD

**Issue by lightningasic** [nginnever/zogminer#8]
here is log info:
root@st:~# zcash-miner -stratum=stratum+tcp://zmine.io:1337 -user=tmGUdN9CE1wNb7znydNHYiyw8VzqmApnLrp -printtoconsole -debug

Zcash Miner version v1.0.0-beta2-c2341ba (2016-10-16 19:03:18 +0200)
Connecting to stratum server zmine.io:1337
Connected!
Starting miner
ZcashMinerThread started
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4266250240
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3019828224
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [Ellesmere] with 4266250240 bytes of GPU memory
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Ellesmere(OpenCL 1.2 AMD-APP (2117.7))
Subscribed to stratum server
Target set to 0fffffff00000000000000000000000000000000000000000000000000000000
Received new job #8982-1476957611
Authorized worker tmGUdN9CE1wNb7znydNHYiyw8VzqmApnLrp
[OPENCL]:Printing program log
[OPENCL]:/tmp/OCL2521T5.cl:112:16: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers
    memcpy(&w, src, sizeof(w));
               ^~~
/tmp/OCL2521T5.cl:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^
/tmp/OCL2521T5.cl:252:36: warning: passing 'const uchar *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
            memcpy( S->buf + left, in, fill ); /* Fill buffer */
                                   ^~
/tmp/OCL2521T5.cl:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^
/tmp/OCL2521T5.cl:267:36: warning: passing 'const uchar *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers
            memcpy( S->buf + left, in, inlen );
                                   ^~
/tmp/OCL2521T5.cl:93:31: note: passing argument to parameter 'src' here
void memcpy(void *dest, void *src, size_t len) {
                              ^
3 warnings generated.

Received new job #8983-1476957701
Running Equihash solver with nNonce = 0000000000000000000000000000000075000000000000000000000000000000
[OPENCL]:Running List Generation...100 Times :)
[OPENCL]:Iteration: 0 Result: 3
[OPENCL]:Iteration: 10 Result: 3
[OPENCL]:Iteration: 20 Result: 3
[OPENCL]:Iteration: 30 Result: 3
[OPENCL]:Iteration: 40 Result: 3
[OPENCL]:Iteration: 50 Result: 3
[OPENCL]:Iteration: 60 Result: 3
[OPENCL]:Iteration: 70 Result: 3
[OPENCL]:Iteration: 80 Result: 3
[OPENCL]:Iteration: 90 Result: 3
Kernel run took 83773 ms. (0.011937 H/s)
Running Equihash solver with nNonce = 0000000000000000000000000000000175000000000000000000000000000000
[OPENCL]:Running List Generation...100 Times :)
[OPENCL]:Iteration: 0 Result: 3
^CDisconnecting
Stopping miner
[OPENCL]:Iteration: 10 Result: 3
^C[WARN] read_until: Bad file descriptor
Reconnecting in 3 seconds...
^Cterminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  wait: Interrupted system call
Aborted (core dumped)
root@st:~#

**Comment by nginnever** [comment]
Thanks for the detailed report. I am swapping out the kernels in the next 24 hours and @omaralvarez will be working on updating the opencl host. Things should operate much differently soon!

**Comment by lightningasic** [comment]
here is my email lx@lightningasic.com. its fatser.

**Comment by nginnever** [comment]
duplocate https://github.com/nginnever/zogminer/issues/10
