### ISSUE TITLE
RedHat-based systems' dependencies (CentOS/Fedora)

### ISSUE THREAD

**Issue by ramonhugo** [nginnever/zogminer#83]
You missed to add the dependency: **vim-commom**
Without it the following error occurs:
**xxd: command not found**

**Comment by omaralvarez** [comment]
Thanks, I totally forgot about that. I will add it to the readme.

**Comment by calvintam236** [comment]
`vim-common` should be added for Debian/ Ubuntu as well since Ubuntu 16.04 has no `xxd` package.
