### ISSUE TITLE
Kernel run took 0 ms. (inf H/s)

### ISSUE THREAD

**Issue by zogminer** [nginnever/zogminer#9]
I just ran HEAD (https://github.com/nginnever/zogminer/commit/f6baa2fd0e84751b9346676398636b54d55fb311) with the new kernel on Nvidia GTX 960.
OS is ubuntu 16.04.
It looks like it starts mining for one cycle, and then not any more.
Do I have to run also zcashd? is there a way to see the status of the mining except the log that it spits?

Running the test miner
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 960
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294770688
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073692672
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Number of Platforms:1
[OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 4294770688 bytes of GPU memory
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Running Solver...
Step: 1...
Step: 2...
Step: 3...
Step: 4...
Step: 5...
Step: 6...
Step: 7...
Step: 8...
[OPENCL]:clEnqueueMapBuffer(-36)
Kernel run took 107 ms. (9.34579 H/s)
[OPENCL]:clEnqueueWriteBuffer(-5)
Kernel run took 0 ms. (inf H/s)
[OPENCL]:clEnqueueWriteBuffer(-5)
Kernel run took 0 ms. (inf H/s)
[OPENCL]:clEnqueueWriteBuffer(-5)
Kernel run took 0 ms. (inf H/s)
[OPENCL]:clEnqueueWriteBuffer(-5)
Kernel run took 0 ms. (inf H/s)
[..]

**Comment by omaralvarez** [comment]
I'm guessing there is an error during the second kernel run, and that is why next runs report 0ms. I'll look into that whenever I can. But right now we need to make the kernel work first, this error should not be too tough to fix.

**Comment by zogminer** [comment]
Is there any way to generate more logs in order to see where the bug is? I assume you don't have Nvidia hardware, so I could provide the remote debugging facility :)

**Comment by omaralvarez** [comment]
I need to improve error handling and logging. As soon as I fix that we can take a look. The thing is that fixing it now is not a priority, because if I concentrate on these things I cannot work on the solver (which is priority nº1).

**Comment by huiguorou** [comment]
Hi Guys. Run with AMD 380 single card for 30 minutes very smooth and get 6.23H/S in average. Great job! thanks for the effort put in. jbcheng.

**Comment by nginnever** [comment]
I'll be pushing a new kernel that will be closer to accurate solution times very soon, stay tuned.
